version: "3"
vars:
  BUILD_DIR: "{{ .ROOT_DIR }}/build"
tasks:
  clean:
    cmds:
      - cmake --build "{{ .BUILD_DIR }}" --target clean

  generate:
    cmd: cmake -S "{{ .ROOT_DIR }}" -B "{{ .BUILD_DIR }}"

  build:
    deps:
      - generate
    cmds:
      - cmake --build "{{ .BUILD_DIR }}" --config "{{ .CMAKE_BUILD_TYPE }}"

  template.ts:
    cmds:
      - "{{ .ROOT_DIR }}/dist/translations/generate-template"

  run:
    cmd: "{{ .BUILD_DIR }}/{{ .CMAKE_BUILD_TYPE }}/quran-companion"
