name: 🪲 Bug Report
description: File a bug report
labels:
  - bug
body:
  - type: textarea
    id: prob-desc
    attributes:
      label: The problem
      description: Describe the issue you are experiencing. Provide a
        clear and concise description of what you were trying to do and what
        happened, along with any error messages you encountered.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Release version
      description: Open the 'About Quran Companion' dialog to see the app
        version.
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: Operating system
      description:
        "Enter the specific operating system version you are running (example:
        Windows 10)"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the behavior
      description: Provide steps to reproduce the problem you are experiencing.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    id: logs
    attributes:
      label: Log files
      description: Please upload the log file found at (~/.config/QuranCompanion/qc.log or C:\Users\your-username\Appdata\Local\QuranCompanion\qc.log). You need to upload the file before launching a new app instance as the logs reset every time you launch the app.
      placeholder:
        You can attach log files by clicking this area to highlight it and then
        dragging the files in.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain your problem, if applicable.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem you are experiencing here.
