name: quran-companion
base: core22
version: "1.2.4"
title: Quran Companion
website: https://github.com/0xzer0x/quran-companion
source-code: https://github.com/0xzer0x/quran-companion
contact: youssefessamasu@gmail.com
summary: Cross-platform Quran reader and player
description: |
  Quran Companion is a cross-platform Quran reader and player with recitation download capabilities, verse highlighting, re-sizable Quran font, and a variety of tafsir books and translations.

grade: stable
confinement: strict
architectures: [amd64]
icon: dist/xdg/logo256.png
lint:
  ignore:
    - classic
    - library

apps:
  quran-companion:
    command: usr/bin/quran-companion
    common-id: io.github._0xzer0x.qurancompanion
    desktop: usr/share/applications/io.github._0xzer0x.qurancompanion.desktop
    environment:
      LD_LIBRARY_PATH: "$SNAP/opt/qt6/6.6.1/gcc_64/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$LD_LIBRARY_PATH"
      PULSE_RUNTIME_PATH: "$XDG_RUNTIME_DIR/../pulse"
      XDG_DATA_DIRS: "$SNAP/usr/share:$XDG_DATA_DIRS"
      QT_QPA_PLATFORMTHEME: gtk3
    plugs:
      - audio-playback
      - gsettings
      - desktop
      - wayland
      - x11
      - network
      - opengl

layout:
  /usr/share/libdrm:
    bind: $SNAP/graphics/usr/share/libdrm
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/graphics/usr/share/X11/XErrorDB
  /usr/share/X11/locale:
    symlink: $SNAP/graphics/usr/share/X11/locale
  /usr/share/X11/xkb:
    symlink: $SNAP/usr/share/X11/xkb
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0

parts:
  qt:
    plugin: nil
    build-packages:
      - python3
      - python3-pip
    override-build: >
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin

      echo -en "[Paths]\nPlugins =
      ../../opt/qt6/6.6.1/gcc_64/plugins\nLibraries =
      ../../opt/qt6/6.6.1/gcc_64/lib\nImports =
      ../../opt/qt6/6.6.1/gcc_64/qml\nQml2Imports =
      ../../opt/qt6/6.6.1/gcc_64/qml" > "$SNAPCRAFT_PART_INSTALL/usr/bin/qt.conf"

      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/qt6

      cd $SNAPCRAFT_PART_INSTALL/opt/qt6

      pip install aqtinstall

      aqt install-qt linux desktop 6.6.1 gcc_64 -m qtimageformats qtmultimedia qtnetworkauth
    prime:
      - opt/qt6
      - usr/bin/qt.conf

  metadata:
    plugin: dump
    source: dist/xdg
    organize:
      "*.desktop": usr/share/applications/
      "*.xml": usr/share/metainfo/
      "*logo64.png": usr/share/icons/hicolor/64x64/apps/io.github._0xzer0x.qurancompanion.png
      "*logo128.png": usr/share/icons/hicolor/128x128/apps/io.github._0xzer0x.qurancompanion.png
      "*logo256.png": usr/share/icons/hicolor/256x256/apps/io.github._0xzer0x.qurancompanion.png

  quran-companion:
    plugin: cmake
    source: .
    source-type: git
    source-branch: main
    source-depth: 1
    parse-info:
      [usr/share/metainfo/io.github._0xzer0x.qurancompanion.metainfo.xml]
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_PREFIX_PATH="$CRAFT_STAGE/opt/qt6/6.6.1/gcc_64"
    after:
      - qt
      - metadata
    build-packages:
      - libpulse-dev
      - libsqlite3-dev
      - libegl-dev
      - libfontconfig1-dev
      - libfreetype-dev
      - libglib2.0-dev
      - libglx-dev
      - libvulkan-dev
      - libxcb1-dev
      - libxcb-cursor-dev
      - libxkbcommon-dev
    stage-packages:
      - libpulse0
      - libpulsedsp
      - libfontconfig1
      - libfreetype6
      - libgl1
      - libegl1
      - libopengl0
      - libgtk-3-0
      - libgtk-3-common
      - libgdk-pixbuf-2.0-0
      - libgdk-pixbuf2.0-common
      - libglib2.0-0
      - libx11-6
      - libx11-xcb1
      - libxcb1
      - libxcb-cursor0
      - libxcb-glx0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-util1
      - libxcb-xfixes0
      - libxcb-xkb1
      - libxkbcommon0
      - libxkbcommon-x11-0
      - libwayland-egl1
      - libwayland-client0
      - libwayland-cursor0
      - hicolor-icon-theme
      - adwaita-icon-theme
      - shared-mime-info
      - xdg-user-dirs

  icons:
    plugin: nil
    after:
      - quran-companion
    build-packages:
      - build-essential
      - dpkg-dev
      - gtk-update-icon-cache
      - libglib2.0-bin
      - libgtk-3-0
    stage-packages:
      - libc-bin
      - libgdk-pixbuf-2.0-0
      - libgdk-pixbuf2.0-0
      - libgdk-pixbuf2.0-common
      - libpng-tools
      - libpng16-16
      - libnvidia-egl-wayland1
      - libxkbcommon0
      - shared-mime-info
      - xdg-user-dirs
    override-prime: |
      craftctl default
      usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders --update-cache
      update-mime-database usr/share/mime
      glib-compile-schemas usr/share/glib-2.0/schemas
      for theme in usr/share/icons/*; do
        if [ -f "$theme/index.theme" ] && [ ! -f "$theme/icon-theme.cache" ]; then
          update-icon-caches "$theme"
        fi
      done
