name: quran-companion
base: core22
version: '1.1.11'
title: Quran Companion
website: https://github.com/0xzer0x/quran-companion
source-code: https://github.com/0xzer0x/quran-companion
contact: youssefessamasu@gmail.com
summary: Quran offline reader and player
description: |
   Quran Companion is a cross-platform Quran reader and listener with recitation download capabilities, verse highlighting, re-sizable Quran font, and a variety of tafsir books and translations.

grade: stable
confinement: strict
architectures: [amd64]
icon: dist/xdg/logo256.png

apps:
  quran-companion:
    command: usr/bin/quran-companion
    common-id: io.github._0xzer0x.qurancompanion
    desktop: usr/share/applications/io.github._0xzer0x.qurancompanion.desktop
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio"
      PULSE_RUNTIME_PATH: "$XDG_RUNTIME_DIR/../pulse"
      QT_QPA_PLATFORMTHEME: gtk3
    plugs:
      - audio-playback
      - desktop
      - desktop-legacy
      - network
      - opengl
      - unity7
      - gsettings
      - wayland
      - x11

plugs: # plugs for theming
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

parts:
  quran-companion:
    plugin: cmake
    source: .
    source-type: git
    parse-info: [usr/share/metainfo/io.github._0xzer0x.qurancompanion.metainfo.xml]
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
    after:
      - qt
      - metadata
  
  metadata:
    plugin: dump
    source: dist/xdg
    organize:
      '*.desktop' : usr/share/applications/
      '*.xml' : usr/share/metainfo/
      '*logo64.png' : usr/share/icons/hicolor/64x64/apps/io.github._0xzer0x.qurancompanion.png
      '*logo128.png' : usr/share/icons/hicolor/128x128/apps/io.github._0xzer0x.qurancompanion.png
      '*logo256.png' : usr/share/icons/hicolor/256x256/apps/io.github._0xzer0x.qurancompanion.png
  
  qt:
    plugin: nil
    build-packages:
      - libaudio-dev
      - libao-dev
      - libpcaudio-dev
      - libasound2-dev
      - libavdevice-dev
      - libvpx-dev
      - libvdpau-dev
      - libva-dev
      - libudfread-dev
      - libtwolame-dev
      - libtheora-dev
      - libswscale-dev
      - libswresample-dev
      - libssh-gcrypt-dev
      - libsrt-gnutls-dev
      - libspeex-dev
      - libsodium-dev
      - libsnappy-dev
      - libshine-dev
      - librsvg2-dev
      - librabbitmq-dev
      - libpgm-dev
      - libopenmpt-dev
      - libopenjp2-7-dev
      - libnuma-dev
      - libnorm-dev
      - libmpg123-dev
      - libmfx-dev
      - libgme-dev
      - libdav1d-dev
      - libchromaprint-dev
      - libcodec2-dev
      - libbluray-dev
      - libavutil-dev
      - libavformat-dev
      - libavcodec-dev
      - libaom-dev
      - ocl-icd-opencl-dev
      - libopus-dev
      - libavutil-dev
      - libavformat-dev
      - libavcodec-dev
      - libasound2-dev
      - libpulse-dev
      - libopenal-dev
      - libsqlite3-dev
      - libdbus-1-dev
      - libegl-dev
      - libfontconfig1-dev
      - libfreetype-dev
      - libglx-dev
      - libgtk-3-dev
      - libharfbuzz-dev
      - libice-dev
      - libicu-dev
      - liblcms2-dev
      - libopengl-dev
      - libpcre2-dev
      - libpng-dev
      - libsm-dev
      - libssl-dev
      - libvulkan-dev
      - libwayland-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxcb-composite0-dev
      - libxcb1-dev
      - libxcb-cursor-dev
      - libxcb-glx0-dev
      - libxcb-icccm4-dev
      - libxcb-image0-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-render0-dev
      - libxcb-render-util0-dev
      - libxcb-shape0-dev
      - libxcb-shm0-dev
      - libxcb-sync-dev
      - libxcb-util-dev
      - libxcb-xfixes0-dev
      - libxcb-xkb-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - libxext-dev
      - libxi-dev
      - libxinerama-dev
      - zlib1g-dev
    stage-packages:
      - libxcomposite1
      - libxcursor1
      - libaudio2
      - libao4
      - libpcaudio0
      - libasound2
      - libavdevice58
      - libwebpmux3
      - libvpx7
      - libvorbisfile3
      - libvdpau1
      - libva-x11-2
      - libudfread0
      - libtwolame0
      - libtheora0
      - libswscale5
      - libswresample3
      - libssh-gcrypt-4
      - libspeex1
      - libsodium23
      - libsnappy1v5
      - libshine3
      - librsvg2-2
      - librabbitmq4
      - libpgm-5.3-0
      - libopenmpt0
      - libopenjp2-7
      - libnuma1
      - libnorm1
      - libmpg123-0
      - libmfx1
      - libgme0
      - libdav1d5
      - libchromaprint1
      - libcodec2-1.0
      - libbluray2
      - libavutil56
      - libavformat58
      - libavcodec58
      - libaom3
      - ocl-icd-libopencl1
      - libpulse0
      - libpulsedsp
      - libdbus-1-3
      - libegl1
      - libfontconfig1
      - libfreetype6
      - libglx0
      - libgtk-3-0
      - libharfbuzz0b
      - libice6
      - libicu70
      - liblcms2-2
      - libopengl0
      - libpcre2-16-0
      - libpng16-16
      - libsm6
      - libssl3
      - libvulkan1
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwayland-server0
      - libx11-6
      - libx11-xcb1
      - libxcb1
      - libxcb-cursor0
      - libxcb-glx0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-util1
      - libxcb-xfixes0
      - libxcb-xkb1
      - libxkbcommon0
      - libxkbcommon-x11-0
      - zlib1g
    override-pull: |
      QT=6.5.3
      git clone -b v${QT} --depth=1 https://code.qt.io/qt/qt5.git .
      git submodule update --init --recursive --depth=1 qtbase qtdeclarative qtwayland qtimageformats qtsvg qtmultimedia qtshadertools qttools
    override-build: |
      ./configure \
        -prefix /usr \
        -libdir /usr/lib/$CRAFT_ARCH_TRIPLET \
        -release \
        -opensource \
        -confirm-license \
        -no-feature-getentropy \
        -no-feature-renameat2 \
        -no-feature-statx \
        -openssl-linked \
        -nomake examples \
        -nomake tests \
        
      cmake --build . -j$CRAFT_PARALLEL_BUILD_COUNT
      DESTDIR="$CRAFT_PART_INSTALL" cmake --install .
    prime:
      - -./usr/bin
      - -./usr/doc
      - -./usr/include
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/cmake
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/metatypes
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/*.a
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/*.la
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/*.so
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/*.prl
      - -./usr/libexec
      - -./usr/mkspecs
      - -./usr/modules
